baseURL = 'https://macek.io/'
languageCode = 'en-us'
title = "Dawid's ramblings"
theme = 'minimal-blog'

# Taxonomies
[taxonomies]
  tag = "tags"
  year = "years"

# Taxonomy permalinks
[permalinks]
  years = "/posts/:slug/"

# Site parameters
[params]
  author = "Dawid Macek"
  email = "dawidmacek42@gmail.com"
  github = "https://github.com/Palkovsky"
  linkedin = "https://www.linkedin.com/in/dawid-macek-8a1143205/"

[pagination]
  disableAliases = false
  pagerSize = 50
  path = 'page'

# Menu configuration
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 20
  [[menu.main]]
    name = "Resume"
    url = "/resume.pdf"
    weight = 30